# Generated by Django 4.2 on 2023-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=140, unique=True),
        ),
    ]
